version: '3.1'

services:
  mongo:
    image: mongo:5.0.13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: testing
    ports:
      - 27017:27017
    # We can use init scripts if the need arises
    #volumes:
      #- ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
