.PHONY: clean

all: ctfe2 enum1 templates3_1 explicit-templ3_2 stack3_3 def-templ3_4 static-if4_1

enum1: enum1.d
	dmd $^

ctfe2: ctfe2.d
	dmd $^

templates3_1: templates3_1.d
	dmd $^

explicit-templ3_2: explicit-templ3_2.d
	dmd $^

stack3_3: stack3_3.d
	dmd $^

def-templ3_4: def-templ3_4.d
	dmd $^

static-if4_1: static-if4_1.d
	dmd $^

isexp5_1: isexp5_1.d
	dmd $^

isexp-conv5_2: isexp-conv5_2.d
	dmd $^

typeof6_1: typeof6_1.d
	dmd $^

templ-constraints7_1: templ-constraints7_1.d
	dmd $^

clean:
	rm -f ctfe2.o ctfe2 enum1.o enum1 templates3_1.o templates3_1 \
		explicit-templ3_2.o explicit-templ3_2 stack3_3.o stack3_3 \
		def-templ3_4.o def-templ3_4 static-if4_1.o static-if4_1 \
		isexp5_1.o isexp5_1 isexp-conv5_2.o isexp-conv5_2 typeof6_1.o typeof6_1 \
		templ-constraints7_1.o templ-constraints7_1



